kind: "Template"
apiVersion: "v1"

parameters:
- name: APP_NAME
  displayName: "Application name"
  description: "Name of your application"
  required: true
- name: SERVICE_URL
  displayName: "Service URL"
  description: ""
  value: ""

objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
    annotations:
      description: "Exposes and load balances the application pods"
      service.alpha.openshift.io/dependencies: '[{"name": "mongodb", "namespace": "", "kind": "Service"}]'
  spec:
    ports:
    - name: "web"
      port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: "${APP_NAME}"
- kind: Route
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
  spec:
    host: "${SERVICE_URL}"
    path: /
    to:
      kind: "Service"
      name: "${APP_NAME}"
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
  spec:
    strategy:
      type: Rolling
    triggers: {}
    replicas: 1
    selector:
      deploymentConfig: "${APP_NAME}"
    template:
      metadata:
        name: "${APP_NAME}"
        labels:
          app: "${APP_NAME}"
          deploymentConfig: "${APP_NAME}"
      spec:
        containers:
        - name: "${APP_NAME}"
          image: " "
          resources:
            limits:
              memory: "1Mi"
          livenessProbe:
            exec:
              command:
              - "return true"
          
