kind: "Template"
apiVersion: "v1"
metadata:
  name: "mongodb-deployment"
  creationTimestamp: null
  annotations:
    description: "Deployment template for mongodb service."
    version: "1.0.0"

parameters:
- name: "DATABASE_SERVICE_NAME"
  displayName: "Database Service Name"
  value: "mongodb"
- name: "DATABASE_USER"
  displayName: "MongoDB Username"
  description: "Username for MongoDB user that will be used for accessing the database."
  value: "nodejsuser"
- name: "DATABASE_PASSWORD"
  displayName: "MongoDB Password"
  description: "Password for the MongoDB user."
  value: "nodejs1password"
- name: "DATABASE_NAME"
  displayName: "Database Name"
  value: "nodejsexdb"
- name: "DATABASE_ADMIN_PASSWORD"
  displayName: "Database Administrator Password"
  description: "Password for the database admin user."
  value: "nodejs0adminpassword"
- name: "MEMORY_MONGODB_LIMIT"
  displayName: "Memory Limit (MongoDB)"
  description: "Maximum amount of memory the MongoDB container can use."
  value: "512Mi"

objects:
- kind: "Service"
  apiVersion: "v1"
  metadata:
    name: "${DATABASE_SERVICE_NAME}"
    annotations:
      description: "Exposes the database server"
  spec:
    ports:
    - name: "mongodb"
      port: 27017
      targetPort: 27017
    selector:
      name: "${DATABASE_SERVICE_NAME}"
- kind: "DeploymentConfig"
  apiVersion: "v1"
  metadata:
    name: "${DATABASE_SERVICE_NAME}"
    annotations:
      description: "Defines how to deploy the database"
  spec:
    strategy:
      type: "Recreate"
    triggers:
    - type: "ImageChange"
      imageChangeParams:
        automatic: true
        containerNames:
          - "mongodb"
        from:
          kind: "ImageStreamTag"
          namespace: "openshift"
          name: "mongodb:2.6"
    - type: "ConfigChange"
    replicas: 1
    selector:
      name: "${DATABASE_SERVICE_NAME}"
    template:
      metadata:
        name: "${DATABASE_SERVICE_NAME}"
        labels:
          name: "${DATABASE_SERVICE_NAME}"
      spec:
        containers:
        - name: "mongodb"
          image: " "
          ports:
          - containerPort: 27017
          env:
          - name: "MONGODB_USER"
            value: "${DATABASE_USER}"
          - name: "MONGODB_PASSWORD"
            value: "${DATABASE_PASSWORD}"
          - name: "MONGODB_DATABASE"
            value: "${DATABASE_NAME}"
          - name: "MONGODB_ADMIN_PASSWORD"
            value: "${DATABASE_ADMIN_PASSWORD}"
          readinessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 3
            exec:
              command:
              - "/bin/sh"
              - "-i"
              - "-c"
              - "mongostat --host 127.0.0.1 -u admin -p ${DATABASE_ADMIN_PASSWORD} -n 1 --noheaders"
          livenessProbe:
            timeoutSeconds: 1
            initialDelaySeconds: 30
            tcpSocket:
              port: 27017
          resources:
            limits:
              memory: "${MEMORY_MONGODB_LIMIT}"
          volumeMounts:
            - name: "${DATABASE_SERVICE_NAME}-data"
              mountPath: "/var/lib/mongodb/data"
        volumes:
          - name: "${DATABASE_SERVICE_NAME}-data"
            emptyDir:
              medium: ""
