apiVersion: v1
kind: Template
parameters:
- name: "APP_NAME"
  displayName: "Application name"
  description: "Name of your application"
  value: nodejs-ex

objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}

- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    strategy:
      type: Source
      sourceStrategy:
        from:
          kind: DockerImage
          name: registry.access.redhat.com/openshift3/nodejs-010-rhel7:latest
    source:
      type: Binary
    output:
      to:
        kind: ImageStreamTag
        name: nodejs-ex:latest
